apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-steam-game-picker
  namespace: steam-game-picker-bot-namespace
  labels:
    app: discord-bot-steam-game-picker
spec:
  selector:
    matchLabels:
      app: discord-bot-steam-game-picker
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: discord-bot-steam-game-picker
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: discord-bot-steam-game-picker
          image: steam-game-picker-bot:latest
          imagePullPolicy: Never # Never try to pull the image, instead use the local version of the Docker image
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
      restartPolicy: Always
